set autowrite
set cmdheight=2
set colorcolumn=80
set cursorline
set hidden
set ignorecase
set list
set listchars=tab:→\ ,nbsp:␣,trail:•,precedes:«,extends:»
set mouse=a
set nobackup
set noshowmode
set noswapfile
set nowrap
set number
set relativenumber
set scrolloff=8
set signcolumn=yes
set smartcase
set smartindent
set splitbelow
set splitright
set updatetime=300
